### ISSUE TITLE
Create a BaseModel with timestamp fields. 

### ISSUE THREAD

**Issue by Jaskaranrehal** [mkhullar89/online_skill_development#2]
Create a abstract BaseModel with created_at and updated_at fields. We'll use this model mostly for new models.

**Comment by Jaskaranrehal** [comment]
[https://github.com/mkhullar89/online_skill_development/blob/c4d517d4fab288651de0b1920857b0f2e76e2145/userman/models.py#L3-L5](url)

@mkhullar89 
Add auto_now and auto_now_add parameters where neccessary.

**Comment by mkhullar89** [comment]
Done Sir
